create table if not exists equips
(
    id     integer generated by default as identity
        constraint equips_pk
            primary key,
    serial text not null,
    type   text not null,
    model  text not null
);

comment on table equips is 'Экземпляры оборудования';